jobs:
  build:
    runs-on: ubuntu-22.04  # Ustaw konkretną wersję Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install west
        run: pip3 install west

      - name: Build firmware for left half
        run: west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD="corne_left"

      - name: Build firmware for right half
        run: west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD="corne_right"
